In [182]:
import tensorflow as tf
import numpy as np
import random
from sklearn import datasets
from pandas import DataFrame

# 1. Data Preparation

In [183]:
x_data = datasets.load_iris().data
y_data = datasets.load_iris().target

In [184]:
x_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [185]:
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 2. Training set & Testing set

### 2.1. Random Shuffle Data set

In [186]:
seed_value = random.randint(1,200)

In [187]:
seed_value

44

In [188]:
np.random.seed(seed_value)
np.random.shuffle(x_data)
np.random.seed(seed_value)
np.random.shuffle(y_data)

In [189]:
x_data

array([[6.7, 3.3, 5.7, 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.6, 3.5, 1. ],
       [5.7, 3. , 4.2, 1.2],
       [6.5, 3. , 5.8, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.3, 2.9, 6.3, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.5, 2.6, 4.4, 1.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.2, 3.4, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 4.1, 1.5, 0.1],
       [6.5, 3.2, 5.1, 2. ],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [5.8, 2.7, 5.1, 1.9],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 3.3, 1.7, 0.5],
       [6.6, 2.9, 4.6, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [6.8, 2.8, 4.8, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [5.2, 3

In [190]:
y_data

array([2, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 2,
       2, 1, 2, 2, 0, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 2, 0,
       0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 2, 2, 2, 1, 1, 0, 2, 0, 1, 2, 2, 2,
       1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 1, 2, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 1, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 0, 0, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 0])

### 2.2. Training set & Testing set

In [191]:
train_x_data = x_data[:-30]
train_y_data = y_data[:-30]

In [192]:
train_x_data

array([[6.7, 3.3, 5.7, 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.6, 3.5, 1. ],
       [5.7, 3. , 4.2, 1.2],
       [6.5, 3. , 5.8, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.3, 2.9, 6.3, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.5, 2.6, 4.4, 1.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.2, 3.4, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 4.1, 1.5, 0.1],
       [6.5, 3.2, 5.1, 2. ],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [5.8, 2.7, 5.1, 1.9],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 3.3, 1.7, 0.5],
       [6.6, 2.9, 4.6, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [6.8, 2.8, 4.8, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [5.2, 3

In [193]:
train_y_data

array([2, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 2,
       2, 1, 2, 2, 0, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 0, 2, 0,
       0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 2, 2, 2, 1, 1, 0, 2, 0, 1, 2, 2, 2,
       1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 1, 2, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 2, 0, 1, 0, 1, 1, 2, 2, 2])

---

In [194]:
test_x_data = x_data[-30:]
test_y_data = y_data[-30:]

In [195]:
test_x_data

array([[5.4, 3.9, 1.3, 0.4],
       [5.8, 2.8, 5.1, 2.4],
       [7.7, 2.8, 6.7, 2. ],
       [6.7, 3.1, 4.7, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [6.4, 2.8, 5.6, 2.1],
       [5.9, 3. , 4.2, 1.5],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 2.5, 4.9, 1.5],
       [5.4, 3.4, 1.5, 0.4],
       [6.4, 2.9, 4.3, 1.3],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.7, 5.1, 1.6],
       [5. , 2.3, 3.3, 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [5.8, 4. , 1.2, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [6.3, 3.3, 6. , 2.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.7, 2.8, 4.5, 1.3],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3. , 5.2, 2. ],
       [5.4, 3. , 4.5, 1.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.9, 3.8, 6.4, 2. ],
       [5.2, 2.7, 3.9, 1.4],
       [5.4, 3.4, 1.7, 0.2]])

In [196]:
test_y_data

array([0, 2, 2, 1, 2, 2, 1, 2, 1, 0, 1, 2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 0])

### 2.3. See Training set & Testing set

In [197]:
temp_train_set = DataFrame(train_x_data, columns=['Sepal_length', 'Sepal_width', 'Petal_length', 'Petal_width'])
temp_train_set['Species'] = train_y_data

In [198]:
temp_train_set

Sepal_length  Sepal_width  Petal_length  Petal_width  Species
0             6.7          3.3           5.7          2.5        2
1             4.9          3.1           1.5          0.1        0
2             5.7          2.6           3.5          1.0        1
3             5.7          3.0           4.2          1.2        1
4             6.5          3.0           5.8          2.2        2
..            ...          ...           ...          ...      ...
115           7.0          3.2           4.7          1.4        1
116           6.4          3.2           4.5          1.5        1
117           7.2          3.2           6.0          1.8        2
118           6.5          3.0           5.5          1.8        2
119           6.4          3.2           5.3          2.3        2

[120 rows x 5 columns]

In [199]:
temp_test_set = DataFrame(test_x_data, columns=['Sepal_length', 'Sepal_width', 'Petal_length', 'Petal_width'])
temp_test_set['Correct Species'] = test_y_data
temp_test_set['Predicted Species'] = np.array('x')

In [200]:
temp_test_set

Sepal_length  Sepal_width  Petal_length  Petal_width  Correct Species  \
0            5.4          3.9           1.3          0.4                0   
1            5.8          2.8           5.1          2.4                2   
2            7.7          2.8           6.7          2.0                2   
3            6.7          3.1           4.7          1.5                1   
4            7.4          2.8           6.1          1.9                2   
5            6.4          2.8           5.6          2.1                2   
6            5.9          3.0           4.2          1.5                1   
7            6.3          2.8           5.1          1.5                2   
8            6.3          2.5           4.9          1.5                1   
9            5.4          3.4           1.5          0.4                0   
10           6.4          2.9           4.3          1.3                1   
11           6.3          2.5           5.0          1.9                2   
12           6.0          2.7           5.1          1.6                1   
13           5.0          2.3           3.3          1.0                1   
14           6.3          2.9           5.6          1.8                2   
15           6.8          3.2           5.9          2.3                2   
16           5.8          4.0           1.2          0.2                0   
17           4.9          3.0           1.4          0.2                0   
18           4.9          2.4           3.3          1.0                1   
19           6.3          3.3           6.0          2.5                2   
20           7.2          3.6           6.1          2.5                2   
21           5.8          2.7           4.1          1.0                1   
22           5.7          2.8           4.5          1.3                1   
23           6.9          3.2           5.7          2.3                2   
24           6.5          3.0           5.2          2.0                2   
25           5.4          3.0           4.5          1.5                1   
26           5.7          2.9           4.2          1.3                1   
27           7.9          3.8           6.4          2.0                2   
28           5.2          2.7           3.9          1.4                1   
29           5.4          3.4           1.7          0.2                0   

   Predicted Species  
0                  x  
1                  x  
2                  x  
3                  x  
4                  x  
5                  x  
6                  x  
7                  x  
8                  x  
9                  x  
10                 x  
11                 x  
12                 x  
13                 x  
14                 x  
15                 x  
16                 x  
17                 x  
18                 x  
19                 x  
20                 x  
21                 x  
22                 x  
23                 x  
24                 x  
25                 x  
26                 x  
27                 x  
28                 x  
29                 x

# 3. Build NN

### 3.1. Data Type Conversion

In [201]:
train_x_data_cast = tf.cast(train_x_data, tf.float32)
test_x_data_cast = tf.cast(test_x_data, tf.float32)

In [202]:
train_x_data_cast

<tf.Tensor: shape=(120, 4), dtype=float32, numpy=
array([[6.7, 3.3, 5.7, 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.6, 3.5, 1. ],
       [5.7, 3. , 4.2, 1.2],
       [6.5, 3. , 5.8, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.3, 2.9, 6.3, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.5, 2.6, 4.4, 1.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.2, 3.4, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 4.1, 1.5, 0.1],
       [6.5, 3.2, 5.1, 2. ],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [5.8, 2.7, 5.1, 1.9],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 3.3, 1.7, 0.5],
       [6.6, 2.9, 4.6, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [6.8, 2.8, 4.8, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1,

In [203]:
test_x_data_cast

<tf.Tensor: shape=(30, 4), dtype=float32, numpy=
array([[5.4, 3.9, 1.3, 0.4],
       [5.8, 2.8, 5.1, 2.4],
       [7.7, 2.8, 6.7, 2. ],
       [6.7, 3.1, 4.7, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [6.4, 2.8, 5.6, 2.1],
       [5.9, 3. , 4.2, 1.5],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 2.5, 4.9, 1.5],
       [5.4, 3.4, 1.5, 0.4],
       [6.4, 2.9, 4.3, 1.3],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.7, 5.1, 1.6],
       [5. , 2.3, 3.3, 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [5.8, 4. , 1.2, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [6.3, 3.3, 6. , 2.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.7, 2.8, 4.5, 1.3],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3. , 5.2, 2. ],
       [5.4, 3. , 4.5, 1.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.9, 3.8, 6.4, 2. ],
       [5.2, 2.7, 3.9, 1.4],
       [5.4, 3.4, 1.7, 0.2]], dtype=float32)>

### 3.2. Define NN Parameters

In [204]:
train_batches = tf.data.Dataset.from_tensor_slices((train_x_data_cast, train_y_data)).batch(32)

In [205]:
test_batches = tf.data.Dataset.from_tensor_slices((test_x_data_cast, test_y_data)).batch(32)

In [206]:
# Random
w = tf.Variable(tf.random.truncated_normal([4, 3], stddev=0.1))

In [207]:
# Random
b = tf.Variable(tf.random.truncated_normal([3], stddev=0.1))

In [208]:
learnin_rate = 0.1

In [209]:
train_rounds = 500

In [210]:
predicted_result = []

### 3.3. Training

In [211]:
for train_round in range(train_rounds):
    for step, (x1, y1) in enumerate(train_batches):
        with tf.GradientTape() as tape:
            y = tf.matmul(x1, w) + b
            y = tf.nn.softmax(y)
            y_correct = tf.one_hot(y1, depth=3)
            loss = tf.reduce_mean(tf.square(y_correct - y))
        grads = tape.gradient(loss, [w, b])
        w.assign_sub(learnin_rate * grads[0])
        b.assign_sub(learnin_rate * grads[1])

### 3.4. Testing

In [212]:
for x2, y2 in test_batches:
    y = tf.matmul(x2, w) + b
    y = tf.nn.softmax(y)
    predicted_result.append(tf.argmax(y, axis=1))

### 3.5. Show

In [213]:
predicted_result

[<tf.Tensor: shape=(30,), dtype=int64, numpy=
 array([0, 2, 2, 1, 2, 2, 1, 1, 1, 0, 1, 2, 2, 1, 2, 2, 0, 0, 1, 2, 2, 1,
        1, 2, 2, 1, 1, 2, 1, 0], dtype=int64)>]

In [214]:
temp_test_set['Predicted Species'] = np.asarray(predicted_result).T

In [215]:
temp_test_set

Sepal_length  Sepal_width  Petal_length  Petal_width  Correct Species  \
0            5.4          3.9           1.3          0.4                0   
1            5.8          2.8           5.1          2.4                2   
2            7.7          2.8           6.7          2.0                2   
3            6.7          3.1           4.7          1.5                1   
4            7.4          2.8           6.1          1.9                2   
5            6.4          2.8           5.6          2.1                2   
6            5.9          3.0           4.2          1.5                1   
7            6.3          2.8           5.1          1.5                2   
8            6.3          2.5           4.9          1.5                1   
9            5.4          3.4           1.5          0.4                0   
10           6.4          2.9           4.3          1.3                1   
11           6.3          2.5           5.0          1.9                2   
12           6.0          2.7           5.1          1.6                1   
13           5.0          2.3           3.3          1.0                1   
14           6.3          2.9           5.6          1.8                2   
15           6.8          3.2           5.9          2.3                2   
16           5.8          4.0           1.2          0.2                0   
17           4.9          3.0           1.4          0.2                0   
18           4.9          2.4           3.3          1.0                1   
19           6.3          3.3           6.0          2.5                2   
20           7.2          3.6           6.1          2.5                2   
21           5.8          2.7           4.1          1.0                1   
22           5.7          2.8           4.5          1.3                1   
23           6.9          3.2           5.7          2.3                2   
24           6.5          3.0           5.2          2.0                2   
25           5.4          3.0           4.5          1.5                1   
26           5.7          2.9           4.2          1.3                1   
27           7.9          3.8           6.4          2.0                2   
28           5.2          2.7           3.9          1.4                1   
29           5.4          3.4           1.7          0.2                0   

    Predicted Species  
0                   0  
1                   2  
2                   2  
3                   1  
4                   2  
5                   2  
6                   1  
7                   1  
8                   1  
9                   0  
10                  1  
11                  2  
12                  2  
13                  1  
14                  2  
15                  2  
16                  0  
17                  0  
18                  1  
19                  2  
20                  2  
21                  1  
22                  1  
23                  2  
24                  2  
25                  1  
26                  1  
27                  2  
28                  1  
29                  0